name: Callable Template Workflow

run-name: Callable Template Workflow

on:
  # Этот тип события говорит, что данный workflow будет вызываться на исполнение только другим workflow
  workflow_call:
    # эти данные получаем из вызывающего workflow
    secrets:
      PASSWORD:
        description: "Secure password"
        required: true

jobs:
  show_incoming_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show password
        run: echo "${{ secrets.PASSWORD }}"
      - name: Show GitHub Repo
        run: echo "${{ toJSON(github) }}"
  # смотрим содержимое репозитория
  show_current_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -a
